```
sequenceDiagram
    participant browser
    participant server

    Note left of browser: new_note_spa
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa
    activate server  
    Note left of server: Server save the new note
    server-->>browser: 201 created
    Note left of browser: Render the new note
    deactivate server
```
